server:
  port: 8080

spring:
  data:
      redis:
        host: steinseye.top
        port: 26379
        password: 8f8H2yJGLjHmZAMf
        database: 0
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 启用服务发现定位器，方便动态路由
      routes:
        - id: credit-user
          uri: lb://credit-user
          filters:
            - StripPrefix=2
          predicates:
            - Path=/api/user/**

        - id: credit-product
          uri: lb://credit-product
          filters:
            - StripPrefix=2
          predicates:
            - Path=/api/product/**

        - id: credit-notification
          uri: lb://credit-notification
          filters:
            - StripPrefix=2
          predicates:
            - Path=/api/notification/**

        - id: credit-trade
          uri: lb://credit-trade
          filters:
            - StripPrefix=2
          predicates:
            - Path=/api/trade/**

        - id: credit-dispute
          uri: lb://credit-dispute
          filters:
            - StripPrefix=2
          predicates:
            - Path=/api/dispute/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true

whitelist:
  # 登录与验证接口（兼容网关转发前缀）
  - "/**/api/auth/login"
  - "/**/api/auth/validate"
  
  # Swagger 相关资源（全路径模糊匹配）
  - "/**/v3/api-docs/**"        # 建议后面加 /**，有些插件会带子路径
  - "/**/swagger-ui.html"
  - "/**/swagger-ui/**"
  - "/**/webjars/**"            # 静态资源放行
  - "/**/swagger-resources/**"  # Swagger 资源定义接口

  