server:
  port: 8080

spring:
  data:
      redis:
        host: steinseye.top
        port: 26379
        password: 8f8H2yJGLjHmZAMf
        database: 0
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 启用服务发现定位器，方便动态路由
      routes:
        - id: credit-user
          uri: lb://credit-user
          filters:
            - StripPrefix=2
          predicates:
            - Path=/api/user/**

        - id: credit-product
          uri: lb://credit-product
          filters:
            - StripPrefix=2
          predicates:
            - Path=/api/product/**

        - id: credit-notification
          uri: lb://credit-notification
          filters:
            - StripPrefix=2
          predicates:
            - Path=/api/notification/**

        - id: credit-trade
          uri: lb://credit-trade
          filters:
            - StripPrefix=2
          predicates:
            - Path=/api/trade/**

        - id: credit-dispute
          uri: lb://credit-dispute
          filters:
            - StripPrefix=2
          predicates:
            - Path=/api/dispute/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - "*.steinseye.top"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true

whitelist:
  # 登录与验证接口（兼容网关转发前缀）
  - "/**/api/auth/login"
  - "/**/api/auth/validate"
  
  # Swagger 相关资源（全路径模糊匹配）
  - "/**/v3/api-docs/**"        # 建议后面加 /**，有些插件会带子路径
  - "/**/swagger-ui.html"
  - "/**/swagger-ui/**"
  - "/**/webjars/**"            # 静态资源放行
  - "/**/swagger-resources/**"  # Swagger 资源定义接口
  - "/**/doc.html"

knife4j:
  gateway:
    enabled: true
    # 指定手动配置模式（更精准）
    strategy: manual
    routes:
      - name: 用户中心
        url: /api/user/v3/api-docs
        service-name: credit-user
        context-path: /api/user
        order: 1
      - name: 产品中心
        url: /api/product/v3/api-docs
        service-name: credit-product
        context-path: /api/product
        order: 2
      - name: 通知中心
        url: /api/notification/v3/api-docs
        service-name: credit-notification
        context-path: /api/notification
        order: 3
      - name: 交易中心
        url: /api/trade/v3/api-docs
        service-name: credit-trade
        context-path: /api/trade
        order: 4  
      - name: 争议中心
        url: /api/dispute/v3/api-docs
        service-name: credit-dispute
        context-path: /api/dispute
        order: 5
