server:
  port: 8081
  servlet:
    context-path: /api/user

springdoc:
  swagger-ui:
    path: /swagger-ui.html      # 访问地址：http://ip:8081/swagger-ui.html
    tags-sorter: alpha          # 按字母排序
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs          # 基础元数据地址
  packages-to-scan: cn.edu.cqjtu.cs.credit.user.controller
spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://luo:3306/credit_user_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 6524316